server:
  port: 8083

spring:
  application:
    name: credit-card-service
  output:
    ansi:
      enabled: ALWAYS
  rabbitmq:
    host: ${HOST_RABBITMQ}
    port: ${PORT_RABBITMQ}
    username: ${USER_RABBITMQ}
    password: ${PASSWORD_RABBITMQ}
  datasource:
    url: jdbc:postgresql://localhost:5432/financesdb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: credit_card
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.orm.connections.pooling: warn

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_URL}/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mq:
  queues:
    credit-emission: credit-emission